// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ovypqvbtroeuobbblfoy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im92eXBxdmJ0cm9ldW9iYmJsZm95Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0MDQ5MTIsImV4cCI6MjA2Njk4MDkxMn0.SGS6VwZgrUTdIltpiKxQtWF8h6BWV93OBldYRdHXu74";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});